create database floremipi;
use floremipi;

-- MySQL Script generated by MySQL Workbench
-- 09/22/16 14:03:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema floremipitest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema floremipitest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `floremipi` DEFAULT CHARACTER SET latin1 ;
USE `floremipi` ;

-- -----------------------------------------------------
-- Table `floremipi`.`adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `floremipi`.`adress` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Location` VARCHAR(200) NULL DEFAULT NULL,
  `ZipCode` VARCHAR(200) NULL DEFAULT NULL,
  `City` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `floremipi`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `floremipi`.`article` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NULL DEFAULT NULL,
  `Description` VARCHAR(200) NULL DEFAULT NULL,
  `Category` VARCHAR(200) NULL DEFAULT NULL,
  `Imgsrc` VARCHAR(300) NULL DEFAULT NULL,
  `QuantityInStock` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 83
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `floremipi`.`articleinprogress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `floremipi`.`articleinprogress` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Quantity` INT(11) NOT NULL DEFAULT '0',
  `StartDate` DATE NOT NULL,
  `ReleaseDate` DATE NOT NULL,
  `IdArticle` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IdArticle` (`IdArticle` ASC),
  CONSTRAINT `articleinprogress_ibfk_1`
    FOREIGN KEY (`IdArticle`)
    REFERENCES `floremipi`.`article` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `floremipi`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `floremipi`.`customer` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NOT NULL,
  `FirstName` VARCHAR(200) NOT NULL,
  `Phone` VARCHAR(15) NOT NULL,
  `Email` VARCHAR(200) NOT NULL,
  `IdAdress` INT(11) NULL DEFAULT NULL,
  `Password` VARCHAR(30) NULL DEFAULT NULL,
  `Login` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IdAdress` (`IdAdress` ASC),
  CONSTRAINT `customer_ibfk_1`
    FOREIGN KEY (`IdAdress`)
    REFERENCES `floremipi`.`adress` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `floremipi`.`price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `floremipi`.`price` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `IdArticle` INT(11) NOT NULL,
  `Value` DECIMAL(10,2) NOT NULL,
  `Date` DATE NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IdArticle` (`IdArticle` ASC),
  CONSTRAINT `price_ibfk_1`
    FOREIGN KEY (`IdArticle`)
    REFERENCES `floremipi`.`article` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `floremipi`.`version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `floremipi`.`version` (
  `id` INT(11) NOT NULL,
  `version` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `floremipi`;

DELIMITER $$
USE `floremipi`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `floremipi`.`Trg_deleteArticle`
BEFORE DELETE ON `floremipi`.`article`
FOR EACH ROW
BEGIN

DELETE from articleinprogress where articleinprogress.IdArticle = OLD.Id;
DELETE from price where price.IdArticle = OLD.Id;

END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
